# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/go-service main.go"
  bin = "tmp/go-service"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[color]
  main = "yellow"
